API_NETSCOPE::fix infinite loop when there is no log
VultureProject/vulture-gui pull request #294
Opened 2023-03-08 09:23 UTC by gparain

2023-03-10 10:35 UTC, KGuillemot requested changes

2023-03-10 10:35 UTC, KGuillemot commented on vulture_os/toolkit/api_parser/netskope/netskope.py
> +                self.frontend.last_api_call = to
Please remove this line, last_api_call is handled just below.
We don't want to update last_api_call is there is no logs.

2023-03-13 16:50 UTC, Okraf commented
In this state, ok for me to merge

2023-03-14 08:30 UTC, Okraf submitted a review, later dismissed

2023-03-14 08:52 UTC, frikilax requested changes

2023-03-14 08:52 UTC, frikilax commented on vulture_os/toolkit/api_parser/netskope/netskope.py
> +                break
could you add a logger to clearly state when entering that case?

2023-03-15 13:30 UTC, frikilax approved these changes

2023-03-15 13:31 UTC, merged