[API_PARSER][CSC_DOMAINMANAGER] NEW collector
VultureProject/vulture-gui pull request #326
Opened 2023-06-28 14:54 UTC by 0xanalog

NEW collector **CSC_DOMAINMANAGER**

2023-06-28 14:55 UTC, gparain submitted a review, later dismissed

2023-07-17 18:10 UTC, frikilax requested changes

2023-07-17 18:10 UTC, frikilax commented on vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
> +                    self.frontend.last_api_call = self.last_api_call
lots of complexity and duplicated code, consider simplifying/factorizing
- logs['events'] can be taken and written as soon as it exists and is not null, without any `if...else` conditions
- the `logs['links'].get('next')` can be used as a variable that replaces the current `lock` variable
  - as long as `logs['links'].get('next')` is true, the while continues: 
    - increment `page`
    - get logs
    - write logs
    - update_lock

Also: 
- don't forget to limit the queried period with a limited `to` (if possible with the API, see previous comment)
- check self.evt_stop in while conditions to stop parser if required

2023-07-18 06:30 UTC, frikilax commented on vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
> +from sys import path as sys_path
this seems to be unused

2023-07-18 15:02 UTC, frikilax approved these changes

2023-07-18 15:05 UTC, merged