[API_PARSER][IMPERVA] Fixes
VultureProject/vulture-gui pull request #327
Opened 2023-06-30 15:25 UTC by nlancon

-  Fix duplicates files downloading
-  Fix crash if file does not exist

2023-07-03 07:05 UTC, gparain submitted a review, later dismissed

2023-07-17 16:59 UTC, frikilax requested changes

2023-07-17 16:59 UTC, frikilax commented on vulture_os/toolkit/api_parser/imperva/imperva.py
> +                        self.finish()
This prevents the for loop from doing the other iterations, is that desired?

2023-07-17 16:59 UTC, frikilax commented on vulture_os/toolkit/api_parser/imperva/imperva.py
> +                for file in files_to_download:
the self.evt_stop.is_set() validation disappeared

2023-07-18 15:19 UTC, frikilax approved these changes

2023-07-18 15:20 UTC, merged