Release 1.2.0
VultureProject/vulture-gui pull request #89
Opened 2021-03-11 22:56 UTC by KGuillemot

2021-03-12 10:21 UTC, Raznak approved these changes

2021-03-12 11:48 UTC, frikilax approved these changes

2021-03-12 12:59 UTC, frikilax requested changes

2021-03-12 12:59 UTC, frikilax commented on vulture_os/toolkit/updates/v1.2.0/2_create_default_template.py
> +        node.api_request("toolkit.yara.yara.compile_all_rules")
```suggestion

```

2021-03-12 12:59 UTC, frikilax commented on vulture_os/toolkit/updates/v1.2.0/1_update_portal_conf.py
> +        node.api_request("toolkit.yara.yara.compile_all_rules")
```suggestion

```

2021-03-12 13:16 UTC, frikilax approved these changes

2021-03-13 10:27 UTC, HugoSoszynski approved these changes

2021-03-13 10:31 UTC, merged